name = "safe-impl"
version = "1.4.1"

description = "Ethereum multisig contract--implementation contracts"

[setting.salt]
defaultValue = "0x0000000000000000000000000000000000000000000000000000000000000000"

[contract.SimulateTxAccessor]
artifact = "SimulateTxAccessor"
salt = "<%= settings.salt %>"
create2 = true

[contract.SafeProxyFactory]
artifact = "SafeProxyFactory"
salt = "<%= settings.salt %>"
create2 = true

[contract.TokenCallbackHandler]
artifact = "TokenCallbackHandler"
salt = "<%= settings.salt %>"
create2 = true

[contract.CompatibilityFallbackHandler]
artifact = "CompatibilityFallbackHandler"
salt = "<%= settings.salt %>"
create2 = true

[contract.CreateCall]
artifact = "CreateCall"
salt = "<%= settings.salt %>"
create2 = true

[contract.MultiSend]
artifact = "MultiSend"
salt = "<%= settings.salt %>"
create2 = true

[contract.MultiSendCallOnly]
artifact = "MultiSendCallOnly"
salt = "<%= settings.salt %>"
create2 = true

[contract.SignMessageLib]
artifact = "SignMessageLib"
salt = "<%= settings.salt %>"
create2 = true

[contract.SafeSingleton]
artifact = "Safe"
salt = "<%= settings.salt %>"
create2 = true
